# Generated by Django 4.0.6 on 2022-10-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=10)),
                ('contact', models.IntegerField(default=0)),
                ('sport', models.CharField(max_length=25)),
                ('mem', models.IntegerField(default=0)),
                ('add', models.CharField(max_length=50)),
            ],
        ),
    ]
