# Generated by Django 4.1.2 on 2022-10-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='mem',
            field=models.CharField(max_length=20),
        ),
    ]
